Добавлена поддержка jwt-токена от backend-auth
pridemon/outpost pull request #2
Opened 2022-03-22 12:39 UTC by microphoneabuser

## Ссылки на связанные задачи/пулл реквесты
Ref: #1   

## Статус PR 
READY

## Описание
- Логика авторизации изменена на работу вместе с https://github.com/pridemon/backend-auth
- Добавлена проверка jwt-токена вместо специальной cookie выставленной из логина и пароля 
- Убраны поля логин+пароль, осталась только кнопка "Login", которая редиректит на https://github.com/pridemon/backend-auth для авторизации через github

2022-03-30 19:09 UTC, ont requested changes
Обсудить и добавить проверку полей `iss` и `aud`

2022-03-30 19:09 UTC, ont commented on pkg/jwt/jwt_service.go
> +	var claims JwtClaims
Здесь ряд проблем:
* очень странный код - `claims` парсятся, но не используются
* проверки на подпись скорее всего будет мало - допустим, что наше мобильное приложение получает jwt-токены, тогда "продвинутый" пользователь сможет получить доступ к нашим админкам, положив в cookie jwt токен от любого нашего приложения.

Чтобы этого не происходило нужно:
* на стороне `backend-auth` выставить правильные поля `aud` и `iss`
* на стороне этого сервиса проверять эти поля

Чуть подробнее https://datatracker.ietf.org/doc/html/rfc7519#section-4.1

2022-03-31 15:45 UTC, microphoneabuser commented on pkg/jwt/jwt_service.go
> +	var claims JwtClaims
> * проверки на подпись скорее всего будет мало - допустим, что наше мобильное приложение получает jwt-токены, тогда "продвинутый" пользователь сможет получить доступ к нашим админкам, положив в cookie jwt токен от любого нашего приложения.

В `backend-auth` для oauth `sign_key` хранится в [отдельном поле конфига](https://github.com/pridemon/backend-auth/blob/master/config/config.yml#L131). Поэтому если `sign_key` для авторизации мобильных приложений будет отличаться, то через такой токен не получишь доступ к админкам. К тому же еще и `claims` для oauth отличаются от тех, которые могут использовать мобильные приложения. 
Но да, все равно, наверное, стоит добавить `aud` и `iss` в `claims`.

2022-03-31 16:54 UTC, ont commented on pkg/jwt/jwt_service.go
> +	var claims JwtClaims
Вот это поворот :)   Не, ну так не пойдет. Так будет работать и ключ можно использовать для идентификации источника, но это негибкое решение:
1. ключ это "абракадабра" не несущая информации о источнике (вшивать в ключ название приложения небезопасно с точки зрения криптографии). Вот если бы было ассиметричное шифрование с подписью сертификатом, но это уже другая история, jwt токен использует механизм попроще
2. в любом случае для мобильных приложений уже используется один ключ подписи и проверка будет идти по полю `iss` (и возможно `aud`). Делать много ключей подписи под каждое приложение нерационально.
3. если вдруг захотим написать страницу для получения информации / валидации jwt токена, то с одной подписью работать проще и универсальнее.

2022-03-31 16:56 UTC, ont commented on pkg/jwt/jwt_service.go
> +	var claims JwtClaims
> К тому же еще и claims для oauth отличаются от тех, которые могут использовать мобильные приложения

это да, но outpost их не проверяет и возвращает `true` - дальше внутренний сервис, который закрыт через outpost, может и не проводить своей проверки `jwt` токена (пример - fenek, в котором нет пользователей)

2022-04-05 12:30 UTC, ont approved these changes

2022-04-05 15:14 UTC, merged